### ISSUE TITLE
Faraday 2 support?

### ISSUE THREAD

**Issue by rgaufman** [bhaberer/faraday-digestauth#17]
Faraday 2 changed things quite significantly, any chance of v2 support?

**Comment by bhaberer** [comment]
It's been a number of years since I left the job that required me to make this gem, so I'm not sure that I'd ever add this personally. :-\

**Comment by iMacTia** [comment]
Hi @bhaberer, Faraday core maintainer here 👋 

Thank you a lot for creating this and maintaining it over the years 🙏 !
I've recently been asked a few times about making digest auth available for Faraday 2, and I think with some work this gem could be made compatible.

Would you be OK with adding maintainers to this repository and owners to the rubygems package so we can do some work to make this compatible with Faraday 2.0?
Alternatively, we could also move it under the `lostisland` org if you don't want to be bothered/involved.

@rgaufman I don't have any app using digest auth and only have basic understanding of how it works.
If @bhaberer is happy to have more people maintaining this gem, would you be interested in becoming a maintainer?

**Comment by bhaberer** [comment]
@iMacTia I'm more than happy to add folks here and on rubygems.

**Comment by iMacTia** [comment]
That's great to hear!
I'm happy to spearhead the upgrade so feel free to add me for now.
If @rgaufman or others then want to help with the long-term maintenance, I'm sure we can add them later 👍

**Comment by rgaufman** [comment]
I'm not very familiar with the internals of Faraday but I am going to read the code and see if I can help, it would be great to have digest supported with Faraday as it's the best http library in Ruby in my opinion :)

**Comment by iMacTia** [comment]
@rgaufman I've done some work to support Faraday 2.0, but to my surprise none of the existing tests are currently failing.
You can see the new CI matrix testing both Faraday 1.x and 2.x for all Ruby 3.0+ versions in [this PR](https://github.com/bhaberer/faraday-digestauth/pull/21).

Could you please share more details into exactly what error you're experiencing when using Faraday 2.0 and ideally a small snippet to reproduce? We might be missing some test coverage.
